/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "surface": "#f8f9fb",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b8c4ff",
        "primary": "#00288e",
        "on-primary": "#ffffff",
        "primary-container": "#1e40af",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed-variant": "#173bab",
        "on-primary-container": "#a8b8ff",
        "on-primary-fixed": "#001453",
        "outline": "#757684",
        "outline-variant": "#c4c5d5",
        "on-surface-variant": "#444653",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary": "#006a61",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f2e4",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary-container": "#006f66",
        "tertiary": "#003564",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#004c8b",
        "tertiary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#a4c9ff",
        "on-tertiary-container": "#8fbeff",
        "on-tertiary-fixed": "#001c39",
        "on-tertiary-fixed-variant": "#004883",
        "surface-variant": "#e1e2e4",
        "surface-bright": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-container": "#edeef0",
        "surface-container-low": "#f3f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "surface-tint": "#3755c3",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        "inverse-primary": "#b8c4ff",
        "background": "#f8f9fb",
        "on-background": "#191c1e",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};